name: ml
# to create this conda environment, run `conda env create -f environment.yml`
# to remove, simply do `conda env remote -n ml`
channels:
    - conda-forge
    - defaults
    - anaconda
dependencies:
    - python=3.7
    - pip
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - statsmodels
    - lmfit
    - xgboost
    - scikit-learn
    - jupyter
    - jupyter_contrib_nbextensions
    - autopep8
    - pandas-profiling
    - tqdm
